[relaychain]
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 3565
default_command = "./target/release/parachain-template-node"

[[parachains.collators]]
name = "arauco-01"
ws_port = 9954
port = 35623
