[relaychain]
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 2563
default_command = "./target/release/parachain-template-node"

[[parachains.collators]]
name = "arauco-01"
